language: python
python: 3.6
sudo: false

jobs:
  include:
  - stage: lint
    name: PyLint
    script: pylint server
  - stage: lint
    name: Flake8
    script: flake8 server
  - stage: test
    name: PyTest Runner
    script: tox
  - stage: test
    name: MyPy Type Analysis
    script: mypy server
  - stage: security
    name: Bandit Security Check
    script: bandit -r server
  - stage: security
    name: Safety Dependency Check
    script: safety check
  - stage: deploy
    name: Deploy To Fake
    script: echo "(fake) deployed!"

stages:
  - name: lint
    if: branch != master
  - name: test
    if: branch != master
  - name: security
    if: branch != master
  - name: deploy
    if: branch = master
