language: python
python: 3.6
cache: pip
sudo: false

install: pip install -e ".[testing]"

jobs:
  include:
  - stage: test
    name: PyLint
    script: pylint server
  - stage: test
    name: Flake8
    script: flake8 server
  - stage: test
    name: Test Runner
    script:
    - python -m pytest --cov=server tests
    - codecov
  - stage: test
    name: Type Analysis
    script: mypy server
  - stage: secure
    name: Dependency Warnings
    script: safety check
  - stage: secure
    name: Security Warnings
    script: bandit -r server

stages:
- test
- secure
