language: python
python: 3.6
cache: pip
sudo: false

jobs:
  include:
  - stage: test
    name: PyLint
    script: pylint server
  - stage: test
    name: Flake8
    script: flake8 server
  - stage: test
    name: PyTest Runner
    script: tox
  - stage: test
    name: MyPy Type Analysis
    script: mypy server
  - stage: secure
    name: Bandit Security Check
    script: bandit -r server
  - stage: secure
    name: Safety Dependency Check
    script: safety check

stages:
- test
- secure
