language: python
python:
  - 3.7
cache: pip
sudo: required
dist: xenial
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - pip install git+https://github.com/pypa/pipenv.git
  - pipenv install --dev --three

jobs:
  include:
  - stage: test
    name: PyLint
    script: pipenv run pylint server
  - stage: test
    name: Flake8
    script: pipenv run flake8 server
  - stage: test
    name: Test Runner
    script:
    - pipenv run test
    - pipenv run codecov
  - stage: test
    name: Type Analysis
    script: pipenv run mypy server
  - stage: secure
    name: Dependency Warnings
    script: pipenv run safety check
  - stage: secure
    name: Security Warnings
    script: pipenv run bandit -r server

stages:
- test
- secure
